# Generated by Django 4.1.2 on 2022-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='image',
            field=models.ImageField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
