# Generated by Django 4.1.2 on 2022-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federations', '0002_federation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='image',
            field=models.ImageField(null=True, upload_to='shields'),
        ),
    ]
